#config/doctrine/schema/Model.Interest.dcm.yml
Model\Interest:
    type: entity
    table: interest
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        user_id:
            type: integer
        name:
            type: string
            length: 500
        parent:
            type: string
            length: 500
        occurence:
            type: integer
        last_update:
            type: datetime