#config/doctrine/schema/Model.Token.dcm.yml
Model\Token:
    type: entity
    table: token
    repositoryClass: Repository\TokenRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        type:
            type: integer
        network_id:
            type: integer
            nullable: true
        access_token:
            type: string
            lenght: 1000
        refresh_token:
            type: string
            lenght: 1000
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id