#config/doctrine/schema/Model.Text.dcm.yml
Model\Text:
    type: entity
    table: text
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        user_id:
            type: integer
        content:
            type: string
            lenght: 500
        context:
            type: string
            lenght: 500
            nullable: true
        feeling:
            type: string
            lenght: 500
            nullable: true
        representation:
            type: string
            lenght: 500
            nullable: true
        classification:
            type: string
            lenght: 500
            nullable: true
        relative_id:
            type: integer
            nullable: true
        processed:
            type: integer
            nullable: true
        last_update:
            type: datetime
            options:
                default: CURRENT_TIMESTAMP