#config/doctrine/schema/Model.Location.dcm.yml
Model\Location:
    type: entity
    table: location
    repositoryClass: Repository\LocationRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true
        city:
            type: string
            lenght: 500
            nullable: true
        address:
            type: string
            lenght: 1000
            nullable: true
        country:
            type: string
            lenght: 500
            nullable: true
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id
