#config/doctrine/schema/Model.Video.dcm.yml
Model\Video:
    type: entity
    table: video
    repositoryClass: Repository\VideoRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        direct_link:
            type: string
            lenght: 1000
        context:
            type: string
            lenght: 500
        title:
            type: string
            lenght: 500
        processed:
            type: integer
            nullable: true
            options:
                default: 0
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id