#config/doctrine/schema/Model.Profile.dcm.yml
Model\Profile:
    type: entity
    table: profile
    repositoryClass: Repository\ProfileRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        leader:
            type: string
            lenght: 500
        creative:
            type: string
            lenght: 500
        class:
            type: string
            lenght: 500
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id