#config/doctrine/schema/Model.Match.dcm.yml
Model\Match:
    type: entity
    table: mate
    repositoryClass: Repository\MateRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        match_id:
            type: integer
        compatibility:
            type: integer
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id