#config/doctrine/schema/Model.User.dcm.yml
Model\User:
    type: entity
    table: user
    repositoryClass: Repository\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        first_name:
            type: string
            lenght: 500
        last_name:
            type: string
            lenght: 500
        email:
            type: string
            lenght: 500
        profile_picture:
            type: string
            length: 500
            nullable: true
        facebook_linked:
            type: integer
            options:
                default: 0
        twitter_linked:
            type: integer
            options:
                default: 0
        pinterest_linked:
            type: integer
            options:
                default: 0
        gmail_linked:
            type: integer
            options:
                default: 0
        instagram_linked:
            type: integer
            options:
                default: 0
        last_update:
            type: datetime
