#config/doctrine/schema/Model.Text.dcm.yml
Model\Text:
    type: entity
    table: text
    repositoryClass: Repository\TextRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        network_id:
            type: string
            lenght: 500
            nullable: true
        content:
            type: string
            lenght: 500
        context:
            type: string
            lenght: 500

        is_liked:
            type: boolean
            options:
                default: false
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
    manyToMany:
        textParent:
            targetEntity: Text
            inversedBy: textChild
            joinTable:
                name: text_relatives
                joinColumn:
                    relative_parent:
                        referencedColumnName: id
                        nullable: false
                        unique: false
                inverseJoinColumns:
                    relative_id:
                        referencedColumnName: id
        textChild:
            targetEntity: Text
            mappedBy: textParent






