#config/doctrine/schema/Model.Picture.dcm.yml
Model\Picture:
    type: entity
    table: picture
    repositoryClass: Repository\PictureRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        direct_link:
            type: string
            lenght: 1000
        meta:
            type: string
            lenght: 500
        content:
            type: string
            lenght: 500
        context:
            type: string
            lenght: 500
        processed:
            type: integer
            nullable: true
            options:
                default: 0
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id