#config/doctrine/schema/Model.Text.dcm.yml
Model\Text:
    type: entity
    table: text
    repositoryClass: Repository\TextRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        content:
            type: string
            lenght: 500
        context:
            type: string
            lenght: 500
            nullable: true
        feeling:
            type: string
            lenght: 500
            nullable: true
        representation:
            type: string
            lenght: 500
            nullable: true
        classification:
            type: string
            lenght: 500
            nullable: true
        relative_id:
            type: integer
            nullable: true
        processed:
            type: integer
            nullable: true
            options:
                default: 0
        last_update:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id