<?php

namespace Repository;

/**
 * MateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateRepository extends \Doctrine\ORM\EntityRepository
{
}
