<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function getAllUserExceptOne($em, $id)
  {
    return $em->createQuery('SELECT user.id FROM Model\User user WHERE user.id != ' . $id)
                    ->getResult();
  }
}
